function VKI_buildKeyboardInputs(){var a=this;this.VKI_version="1.11";this.VKI_target=this.VKI_visible="";this.VKI_deadkeysOn=this.VKI_shift=this.VKI_capslock=this.VKI_alternate=this.VKI_dead=false;this.VKI_kt="Portugues";this.VKI_range=false;this.VKI_keyCenter=3;this.VKI_isIE6=this.VKI_isIE=false;this.VKI_isMoz=typeof window.sidebar!="undefined";this.VKI_layout={};this.VKI_layoutDDK={};this.VKI_layout.Arabe=[[["\u0630","\u0651 "],["1","!","\u00a1","\u00b9"],["2","@","\u00b2"],["3","#","\u00b3"],
["4","$","\u00a4","\u00a3"],["5","%","\u20ac"],["6","^","\u00bc"],["7","&","\u00bd"],["8","*","\u00be"],["9","(","\u2018"],["0",")","\u2019"],["-","_","\u00a5"],["=","+","\u00d7","\u00f7"],["Bksp","Bksp"]],[["Tab","Tab"],["\u0636","\u064e"],["\u0635","\u064b"],["\u062b","\u064f"],["\u0642","\u064c"],["\u0641","\u0644"],["\u063a","\u0625"],["\u0639","\u2018"],["\u0647","\u00f7"],["\u062e","\u00d7"],["\u062d","\u061b"],["\u062c","<"],["\u062f",">"],["\\","|"]],[["Caps","Caps"],["\u0634","\u0650"],["\u0633",
"\u064d"],["\u064a","]"],["\u0628","["],["\u0644","\u0644"],["\u0627","\u0623"],["\u062a","\u0640"],["\u0646","\u060c"],["\u0645","/"],["\u0643",":"],["\u0637",'"'],["Enter","Enter"]],[["Shift","Shift"],["\u0626","~"],["\u0621","\u0652"],["\u0624","}"],["\u0631","{"],["\u0644","\u0644"],["\u0649","\u0622"],["\u0629","\u2019"],["\u0648",","],["\u0632","."],["\u0638","\u061f"],["Shift","Shift"]],[[" "," "," "," "],["Alt","Alt"]]];this.VKI_layout.Belgo=[[["\u00b2","\u00b3"],["&","1","|"],["\u00e9","2",
"@"],['"',"3","#"],["'","4"],["(","5"],["\u00a7","6","^"],["\u00e8","7"],["!","8"],["\u00e7","9","{"],["\u00e0","0","}"],[")","\u00b0"],["-","_"],["Bksp","Bksp"]],[["Tab","Tab"],["a","A"],["z","Z"],["e","E","\u20ac"],["r","R"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["^","\u00a8","["],["$","*","]"],["Enter","Enter"]],[["Caps","Caps"],["q","Q"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],["m","M"],["\u00f9","%","\u00b4"],["\u03bc","\u00a3","`"]],
[["Shift","Shift"],["<",">","\\"],["w","W"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],[",","?"],[";","."],[":","/"],["=","+","~"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Neerlandes=[[["@","\u00a7","\u00ac"],["1","!","\u00b9"],["2",'"',"\u00b2"],["3","#","\u00b3"],["4","$","\u00bc"],["5","%","\u00bd"],["6","&","\u00be"],["7","_","\u00a3"],["8","(","{"],["9",")","}"],["0","'"],["/","?","\\"],["\u00b0","~","\u00b8"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q"],
["w","W"],["e","E","\u20ac"],["r","R","\u00b6"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["\u00a8","^"],["*","|"],["<",">"]],[["Caps","Caps"],["a","A"],["s","S","\u00df"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],["+","\u00b1"],["\u00b4","`"],["Enter","Enter"]],[["Shift","Shift"],["]","[","\u00a6"],["z","Z","\u00ab"],["x","X","\u00bb"],["c","C","\u00a2"],["v","V"],["b","B"],["n","N"],["m","M","\u00b5"],[",",";"],[".",":","\u00b7"],["-","="],["Shift",
"Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Dvorak=[[["`","~"],["1","!"],["2","@"],["3","#"],["4","$"],["5","%"],["6","^"],["7","&"],["8","*"],["9","("],["0",")"],["[","{"],["]","}"],["Bksp","Bksp"]],[["Tab","Tab"],["'",'"'],[",","<"],[".",">"],["p","P"],["y","Y"],["f","F"],["g","G"],["c","C"],["r","R"],["l","L"],["/","?"],["=","+"],["\\","|"]],[["Caps","Caps"],["a","A"],["o","O"],["e","E"],["u","U"],["i","I"],["d","D"],["h","H"],["t","T"],["n","N"],["s","S"],["-","_"],["Enter",
"Enter"]],[["Shift","Shift"],[";",":"],["q","Q"],["j","J"],["k","K"],["x","X"],["b","B"],["m","M"],["w","W"],["v","V"],["z","Z"],["Shift","Shift"]],[[" "," "]]];this.VKI_layout.Frances=[[["\u00b2","\u00b3"],["&","1"],["\u00e9","2","~"],['"',"3","#"],["'","4","{"],["(","5","["],["-","6","|"],["\u00e8","7","`"],["_","8","\\"],["\u00e7","9","^"],["\u00e0","0","@"],[")","\u00b0","]"],["=","+","}"],["Bksp","Bksp"]],[["Tab","Tab"],["a","A"],["z","Z"],["e","E","\u20ac"],["r","R"],["t","T"],["y","Y"],["u",
"U"],["i","I"],["o","O"],["p","P"],["^","\u00a8"],["$","\u00a3","\u00a4"],["Enter","Enter"]],[["Caps","Caps"],["q","Q"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],["m","M"],["\u00f9","%"],["*","\u03bc"]],[["Shift","Shift"],["<",">"],["w","W"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],[",","?"],[";","."],[":","/"],["!","\u00a7"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Alemao=[[["^","\u00b0"],["1","!"],["2",'"',"\u00b2"],
["3","\u00a7","\u00b3"],["4","$"],["5","%"],["6","&"],["7","/","{"],["8","(","["],["9",")","]"],["0","=","}"],["\u00df","?","\\"],["\u00b4","`"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q","@"],["w","W"],["e","E","\u20ac"],["r","R"],["t","T"],["z","Z"],["u","U"],["i","I"],["o","O"],["p","P"],["\u00fc","\u00dc"],["+","*","~"],["Enter","Enter"]],[["Caps","Caps"],["a","A"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],["\u00f6","\u00d6"],["\u00e4","\u00c4"],["#","'"]],
[["Shift","Shift"],["<",">","\u00a6"],["y","Y"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M","\u00b5"],[",",";"],[".",":"],["-","_"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Grego=[[["`","~"],["1","!"],["2","@","\u00b2"],["3","#","\u00b3"],["4","$","\u00a3"],["5","%","\u00a7"],["6","^","\u00b6"],["7","&"],["8","*","\u00a4"],["9","(","\u00a6"],["0",")","\u00ba"],["-","_","\u00b1"],["=","+","\u00bd"],["Bksp","Bksp"]],[["Tab","Tab"],[";",":"],["\u03c2",
"^"],["\u03b5","\u0395"],["\u03c1","\u03a1"],["\u03c4","\u03a4"],["\u03c5","\u03a5"],["\u03b8","\u0398"],["\u03b9","\u0399"],["\u03bf","\u039f"],["\u03c0","\u03a0"],["[","{","\u201c"],["]","}","\u201d"],["Enter","Enter"]],[["Caps","Caps"],["\u03b1","\u0391"],["\u03c3","\u03a3"],["\u03b4","\u0394"],["\u03c6","\u03a6"],["\u03b3","\u0393"],["\u03b7","\u0397"],["\u03be","\u039e"],["\u03ba","\u039a"],["\u03bb","\u039b"],["\u0384","\u00a8","\u0385"],["'",'"'],["\\","|","\u00ac"]],[["Shift","Shift"],["<",
">"],["\u03b6","\u0396"],["\u03c7","\u03a7"],["\u03c8","\u03a8"],["\u03c9","\u03a9"],["\u03b2","\u0392"],["\u03bd","\u039d"],["\u03bc","\u039c"],[",","<"],[".",">"],["/","?"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Hebreu=[[["~","`"],["1","!"],["2","@"],["3","#"],["4","$","\u20aa"],["5","%"],["6","^"],["7","&"],["8","*"],["9",")"],["0","("],["-","_"],["=","+"],["\\","|"],["Bksp","Bksp"]],[["Tab","Tab"],["/","Q"],["'","W"],["\u05e7","E","\u20ac"],["\u05e8","R"],["\u05d0",
"T"],["\u05d8","Y"],["\u05d5","U","\u05f0"],["\u05df","I"],["\u05dd","O"],["\u05e4","P"],["]","}"],["[","{"]],[["Caps","Caps"],["\u05e9","A"],["\u05d3","S"],["\u05d2","D"],["\u05db","F"],["\u05e2","G"],["\u05d9","H","\u05f2"],["\u05d7","J","\u05f1"],["\u05dc","K"],["\u05da","L"],["\u05e3",":"],[",",'"'],["Enter","Enter"]],[["Shift","Shift"],["\u05d6","Z"],["\u05e1","X"],["\u05d1","C"],["\u05d4","V"],["\u05e0","B"],["\u05de","N"],["\u05e6","M"],["\u05ea",">"],["\u05e5","<"],[".","?"],["Shift","Shift"]],
[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Hungaro=[[["0","\u00a7"],["1","'","~"],["2",'"',"\u02c7"],["3","+","\u02c6"],["4","!","\u02d8"],["5","%","\u00b0"],["6","/","\u02db"],["7","=","`"],["8","(","\u02d9"],["9",")","\u00b4"],["\u00f6","\u00d6","\u02dd"],["\u00fc","\u00dc","\u00a8"],["\u00f3","\u00d3","\u00b8"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q","\\"],["w","W","|"],["e","E","\u00c4"],["r","R"],["t","T"],["z","Z"],["u","U","\u20ac"],["i","I","\u00cd"],["o","O"],["p","P"],["\u0151",
"\u0150","\u00f7"],["\u00fa","\u00da","\u00d7"],["Enter","Enter"]],[["Caps","Caps"],["a","A","\u00e4"],["s","S","\u0111"],["d","D","\u0110"],["f","F","["],["g","G","]"],["h","H"],["j","J","\u00ed"],["k","K","\u0141"],["l","L","\u0142"],["\u00e9","\u00c9","$"],["\u00e1","\u00c1","\u00df"],["\u0171","\u0170","\u00a4"]],[["Shift","Shift"],["\u00ed","\u00cd","<"],["y","Y",">"],["x","X","#"],["c","C","&"],["v","V","@"],["b","B","{"],["n","N","}"],["m","M","<"],[",","?",";"],[".",":",">"],["-","_","*"],
["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Italiano=[[["\\","|"],["1","!"],["2",'"'],["3","\u00a3"],["4","$","\u20ac"],["5","%"],["6","&"],["7","/"],["8","("],["9",")"],["0","="],["'","?"],["\u00ec","^"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q"],["w","W"],["e","E","\u20ac"],["r","R"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["\u00e8","\u00e9","[","{"],["+","*","]","}"],["Enter","Enter"]],[["Caps","Caps"],["a","A"],["s","S"],["d","D"],["f","F"],["g",
"G"],["h","H"],["j","J"],["k","K"],["l","L"],["\u00f2","\u00e7","@"],["\u00e0","\u00b0","#"],["\u00f9","\u00a7"]],[["Shift","Shift"],["<",">"],["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M"],[",",";"],[".",":"],["-","_"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Lituano=[[["`","~"],["\u0105","\u0104"],["\u010d","\u010c"],["\u0119","\u0118"],["\u0117","\u0116"],["\u012f","\u012e"],["\u0161","\u0160"],["\u0173","\u0172"],["\u016b","\u016a"],["\u201e",
"("],["\u201c",")"],["-","_"],["\u017e","\u017d"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q"],["w","W"],["e","E"],["r","R"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["[","{"],["]","}"],["Enter","Enter"]],[["Caps","Caps"],["a","A"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],[";",":"],["'",'"'],["\\","|"]],[["Shift","Shift"],["\u2013","\u20ac"],["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M"],[",","<"],[".",">"],["/","?"],["Shift",
"Shift"]],[[" "," "]]];this.VKI_layout.Noruegues=[[["|","\u00a7"],["1","!"],["2",'"',"@"],["3","#","\u00a3"],["4","\u00a4","$"],["5","%"],["6","&"],["7","/","{"],["8","(","["],["9",")","]"],["0","=","}"],["+","?"],["\\","`","\u00b4"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q"],["w","W"],["e","E","\u20ac"],["r","R"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["\u00e5","\u00c5"],["\u00a8","^","~"],["Enter","Enter"]],[["Caps","Caps"],["a","A"],["s","S"],["d","D"],["f","F"],["g","G"],["h",
"H"],["j","J"],["k","K"],["l","L"],["\u00f8","\u00d8"],["\u00e6","\u00c6"],["'","*"]],[["Shift","Shift"],["<",">"],["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M","\u03bc","\u039c"],[",",";"],[".",":"],["-","_"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Numpad=[[["$"],["\u00a3"],["\u20ac"],["\u00a5"],["/"],["^"],["Bksp","Bksp"]],[["."],["7"],["8"],["9"],["*"],["<"],["("],["["]],[["="],["4"],["5"],["6"],["-"],[">"],[")"],["]"]],[["0"],["1"],["2"],
["3"],["+"],["Enter","Enter"]],[[" "]]];this.VKI_layoutDDK.Numpad=true;this.VKI_layout["Polones Prog"]=[[["`","~"],["1","!"],["2","@"],["3","#"],["4","$"],["5","%"],["6","^"],["7","&"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q"],["w","W"],["e","E","\u0119","\u0118"],["r","R"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O","\u00f3","\u00d3"],["p","P"],["[","{"],["]","}"],["\\","|"]],[["Caps","Caps"],["a","A","\u0105","\u0104"],["s","S","\u015b","\u015a"],
["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L","\u0142","\u0141"],[";",":"],["'",'"'],["Enter","Enter"]],[["Shift","Shift"],["z","Z","\u017c","\u017b"],["x","X","\u017a","\u0179"],["c","C","\u0107","\u0106"],["v","V"],["b","B"],["n","N","\u0144","\u0143"],["m","M"],[",","<"],[".",">"],["/","?"],["Shift","Shift"]],[[" "," "," "," "],["Alt","Alt"]]];this.VKI_layout.Portugues=[[["`","\u00ac","\u00a6"],["1","!"],["2",'"'],["3","\u00a3"],["4","$","\u20ac"],["5","%"],["6","^"],["7",
"&"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q"],["w","W"],["e","E","\u00e9","\u00c9"],["r","R"],["t","T"],["y","Y"],["u","U","\u00fa","\u00da"],["i","I","\u00ed","\u00cd"],["o","O","\u00f3","\u00d3"],["p","P"],["[","{"],["]","}"],["Enter","Enter"]],[["Caps","Caps"],["a","A","\u00e1","\u00c1"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],["\u00e7","\u00c7"],[";",":"],["'","@"],["#","~"]],[["Shift","Shift"],["\\","|"],
["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M"],[",","<"],[".",">"],["/","?"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Russo=[[["\u0451","\u0401"],["1","!"],["2",'"'],["3","\u2116"],["4",";"],["5","%"],["6",":"],["7","?"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"],["Bksp","Bksp"]],[["Tab","Tab"],["\u0439","\u0419"],["\u0446","\u0426"],["\u0443","\u0423"],["\u043a","\u041a"],["\u0435","\u0415"],["\u043d","\u041d"],["\u0433","\u0413"],["\u0448",
"\u0428"],["\u0449","\u0429"],["\u0437","\u0417"],["\u0445","\u0425"],["\u044a","\u042a"],["Enter","Enter"]],[["Caps","Caps"],["\u0444","\u0424"],["\u044b","\u042b"],["\u0432","\u0412"],["\u0430","\u0410"],["\u043f","\u041f"],["\u0440","\u0420"],["\u043e","\u041e"],["\u043b","\u041b"],["\u0434","\u0414"],["\u0436","\u0416"],["\u044d","\u042d"],["\\","/"]],[["Shift","Shift"],["/","|"],["\u044f","\u042f"],["\u0447","\u0427"],["\u0441","\u0421"],["\u043c","\u041c"],["\u0438","\u0418"],["\u0442","\u0422"],
["\u044c","\u042c"],["\u0431","\u0411"],["\u044e","\u042e"],[".",","],["Shift","Shift"]],[[" "," "]]];this.VKI_layout.Sueco=[[["\u00a8","\u00a8","\u00b8"],["1","!","~"],["2",'"',"\u02c7"],["3","#","^"],["4","$","\u02d8"],["5","%","\u00b0"],["6","&","\u02db"],["7","/","`"],["8","(","\u00b7"],["9",")","\u00b4"],["0","=","\u2033"],["'","?","\u00a8"],["+","*","\u00b8"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q","\\"],["w","W","|"],["e","E","\u20ac"],["r","R"],["t","T"],["z","Z"],["u","U"],["i","I"],["o",
"O"],["p","P"],["\u0161","\u0160","\u00f7"],["\u0111","\u0110","\u00d7"],["Enter","Enter"]],[["Caps","Caps"],["a","A"],["s","S"],["d","D"],["f","F","["],["g","G","]"],["h","H"],["j","J"],["k","K","\u0142"],["l","L","\u0141"],["\u010d","\u010c"],["\u0107","\u0106","\u00df"],["\u017e","\u017d","\u00a4"]],[["Shift","Shift"],["<",">"],["y","Y"],["x","X"],["c","C"],["v","V","@"],["b","B","{"],["n","N","}"],["m","M","\u00a7"],[",",";"],[".",":"],["-","_"],["Shift","Shift"]],[[" "," "," "," "],["AltGr",
"AltGr"]]];this.VKI_layout["Espanhol-SP"]=[[["\u00ba","\u00aa","\\"],["1","!","|"],["2",'"',"@"],["3","'","#"],["4","$","~"],["5","%","\u20ac"],["6","&","\u00ac"],["7","/"],["8","("],["9",")"],["0","="],["'","?"],["\u00a1","\u00bf"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q"],["w","W"],["e","E"],["r","R"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["`","^","["],["+","*","]"],["Enter","Enter"]],[["Caps","Caps"],["a","A"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k",
"K"],["l","L"],["\u00f1","\u00d1"],["\u00b4","\u00a8","{"],["\u00e7","\u00c7","}"]],[["Shift","Shift"],["<",">"],["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M"],[",",";"],[".",":"],["-","_"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout["Turco-F"]=[[["+","*","\u00ac"],["1","!","\u00b9","\u00a1"],["2",'"',"\u00b2"],["3","^","#","\u00b3"],["4","$","\u00bc","\u00a4"],["5","%","\u00bd"],["6","&","\u00be"],["7","'","{"],["8","(","["],["9",")","]"],["0",
"=","}"],["/","?","\\","\u00bf"],["-","_","|"],["Bksp","Bksp"]],[["Tab","Tab"],["f","F","@"],["g","G"],["\u011f","\u011e"],["\u0131","I","\u00b6","\u00ae"],["o","O"],["d","D","\u00a5"],["r","R"],["n","N"],["h","H","\u00f8","\u00d8"],["p","P","\u00a3"],["q","Q","\u00a8"],["w","W","~"],["Enter","Enter"]],[["Caps","Caps"],["u","U","\u00e6","\u00c6"],["i","\u0130","\u00df","\u00a7"],["e","E","\u20ac"],["a","A"," ","\u00aa"],["\u00fc","\u00dc"],["t","T"],["k","K"],["m","M"],["l","L"],["y","Y","\u00b4"],
["\u015f","\u015e"],["x","X","`"]],[["Shift","Shift"],["<",">","|","\u00a6"],["j","J","\u00ab","<"],["\u00f6","\u00d6","\u00bb",">"],["v","V","\u00a2","\u00a9"],["c","C"],["\u00e7","\u00c7"],["z","Z"],["s","S","\u00b5","\u00ba"],["b","B","\u00d7"],[".",":","\u00f7"],[",",";","-"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout["Turco-Q"]=[[['"',"\u00e9","<"],["1","!",">"],["2","'","\u00a3"],["3","^","#"],["4","+","$"],["5","%","\u00bd"],["6","&"],["7","/","{"],["8","(","["],
["9",")","]"],["0","=","}"],["*","?","\\"],["-","_","|"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q","@"],["w","W"],["e","E","\u20ac"],["r","R"],["t","T"],["y","Y"],["u","U"],["\u0131","I","i","\u0130"],["o","O"],["p","P"],["\u011f","\u011e","\u00a8"],["\u00fc","\u00dc","~"],["Enter","Enter"]],[["Caps","Caps"],["a","A","\u00e6","\u00c6"],["s","S","\u00df"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],["\u015f","\u015e","\u00b4"],["i","\u0130"],[",",";","`"]],[["Shift","Shift"],
["<",">","|"],["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M"],["\u00f6","\u00d6"],["\u00e7","\u00c7"],[".",":"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout.Ingles=[[["`","\u00ac","\u00a6"],["1","!"],["2",'"'],["3","\u00a3"],["4","$","\u20ac"],["5","%"],["6","^"],["7","&"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q"],["w","W"],["e","E","\u00e9","\u00c9"],["r","R"],["t","T"],["y","Y"],["u","U","\u00fa",
"\u00da"],["i","I","\u00ed","\u00cd"],["o","O","\u00f3","\u00d3"],["p","P"],["[","{"],["]","}"],["Enter","Enter"]],[["Caps","Caps"],["a","A","\u00e1","\u00c1"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],[";",":"],["'","@"],["#","~"]],[["Shift","Shift"],["\\","|"],["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n","N"],["m","M"],[",","<"],[".",">"],["/","?"],["Shift","Shift"]],[[" "," "," "," "],["AltGr","AltGr"]]];this.VKI_layout["Ingles-EUA"]=[[["`","~"],
["1","!"],["2","@"],["3","#"],["4","$"],["5","%"],["6","^"],["7","&"],["8","*"],["9","("],["0",")"],["-","_"],["=","+"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q"],["w","W"],["e","E"],["r","R"],["t","T"],["y","Y"],["u","U"],["i","I"],["o","O"],["p","P"],["[","{"],["]","}"],["\\","|"]],[["Caps","Caps"],["a","A"],["s","S"],["d","D"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L"],[";",":"],["'",'"'],["Enter","Enter"]],[["Shift","Shift"],["z","Z"],["x","X"],["c","C"],["v","V"],["b","B"],["n",
"N"],["m","M"],[",","<"],[".",">"],["/","?"],["Shift","Shift"]],[[" "," "]]];this.VKI_layout["Ingles-Int"]=[[["`","~"],["1","!","\u00a1","\u00b9"],["2","@","\u00b2"],["3","#","\u00b3"],["4","$","\u00a4","\u00a3"],["5","%","\u20ac"],["6","^","\u00bc"],["7","&","\u00bd"],["8","*","\u00be"],["9","(","\u2018"],["0",")","\u2019"],["-","_","\u00a5"],["=","+","\u00d7","\u00f7"],["Bksp","Bksp"]],[["Tab","Tab"],["q","Q","\u00e4","\u00c4"],["w","W","\u00e5","\u00c5"],["e","E","\u00e9","\u00c9"],["r","R","\u00ae"],
["t","T","\u00fe","\u00de"],["y","Y","\u00fc","\u00dc"],["u","U","\u00fa","\u00da"],["i","I","\u00ed","\u00cd"],["o","O","\u00f3","\u00d3"],["p","P","\u00f6","\u00d6"],["[","{","\u00ab"],["]","}","\u00bb"],["\\","|","\u00ac","\u00a6"]],[["Caps","Caps"],["a","A","\u00e1","\u00c1"],["s","S","\u00df","\u00a7"],["d","D","\u00f0","\u00d0"],["f","F"],["g","G"],["h","H"],["j","J"],["k","K"],["l","L","\u00f8","\u00d8"],[";",":","\u00b6","\u00b0"],["'",'"',"\u00b4","\u00a8"],["Enter","Enter"]],[["Shift","Shift"],
["z","Z","\u00e6","\u00c6"],["x","X"],["c","C","\u00a9","\u00a2"],["v","V"],["b","B"],["n","N","\u00f1","\u00d1"],["m","M","\u00b5"],[",","<","\u00e7","\u00c7"],[".",">"],["/","?","\u00bf"],["Shift","Shift"]],[[" "," "," "," "],["Alt","Alt"]]];this.VKI_deadkey={};this.VKI_deadkey['"']=this.VKI_deadkey["\u00a8"]=[["a","\u00e4"],["e","\u00eb"],["i","\u00ef"],["o","\u00f6"],["u","\u00fc"],["y","\u00ff"],["\u03b9","\u03ca"],["\u03c5","\u03cb"],["A","\u00c4"],["E","\u00cb"],["I","\u00cf"],["O","\u00d6"],
["U","\u00dc"],["Y","\u0178"],["\u0399","\u03aa"],["\u03a5","\u03ab"]];this.VKI_deadkey["~"]=[["a","\u00e3"],["o","\u00f5"],["n","\u00f1"],["A","\u00c3"],["O","\u00d5"],["N","\u00d1"]];this.VKI_deadkey["^"]=[["a","\u00e2"],["e","\u00ea"],["i","\u00ee"],["o","\u00f4"],["u","\u00fb"],["w","\u0175"],["y","\u0177"],["A","\u00c2"],["E","\u00ca"],["I","\u00ce"],["O","\u00d4"],["U","\u00db"],["W","\u0174"],["Y","\u0176"]];this.VKI_deadkey["\u02c7"]=[["c","\u010d"],["s","\u0161"],["z","\u017e"],["r","\u0159"],
["d","\u010f"],["t","\u0165"],["n","\u0148"],["l","\u013e"],["e","\u011b"],["C","\u010c"],["S","\u0160"],["Z","\u017d"],["R","\u0158"],["D","\u010e"],["T","\u0164"],["N","\u0147"],["L","\u013d"],["E","\u011a"]];this.VKI_deadkey["\u02d8"]=[["a","\u0103"],["g","\u011f"],["A","\u0102"],["G","\u011e"]];this.VKI_deadkey["`"]=[["a","\u00e0"],["e","\u00e8"],["i","\u00ec"],["o","\u00f2"],["u","\u00f9"],["A","\u00c0"],["E","\u00c8"],["I","\u00cc"],["O","\u00d2"],["U","\u00d9"]];this.VKI_deadkey["'"]=this.VKI_deadkey["\u00b4"]=
this.VKI_deadkey["\u0384"]=[["a","\u00e1"],["e","\u00e9"],["i","\u00ed"],["o","\u00f3"],["u","\u00fa"],["\u03b1","\u03ac"],["\u03b5","\u03ad"],["\u03b7","\u03ae"],["\u03b9","\u03af"],["\u03bf","\u03cc"],["\u03c5","\u03cd"],["\u03c9","\u03ce"],["A","\u00c1"],["E","\u00c9"],["I","\u00cd"],["O","\u00d3"],["U","\u00da"],["\u0391","\u0386"],["\u0395","\u0388"],["\u0397","\u0389"],["\u0399","\u038a"],["\u039f","\u038c"],["\u03a5","\u038e"],["\u03a9","\u038f"]];this.VKI_deadkey["\u02dd"]=[["o","\u0151"],
["u","\u0171"],["O","\u0150"],["U","\u0170"]];this.VKI_deadkey["\u0385"]=[["\u03b9","\u0390"],["\u03c5","\u03b0"]];this.VKI_deadkey["\u00b0"]=this.VKI_deadkey["\u00ba"]=[["a","\u00e5"],["A","\u00c5"]];for(var e=[document.getElementsByTagName("input"),document.getElementsByTagName("textarea")],f=0,c=0,b;b=e[f++];)if(b)for(var h=0,p="",i;i=b[h++];)if((i.nodeName=="TEXTAREA"||i.type=="text"||i.type=="password")&&i.className.indexOf("keyboardInput")>-1){if(i.id)p=i.id;else{do p="keyboardInputInitiator"+
c++;while(document.getElementById(p));i.id=p}var u=document.createElement("img");u.src=window.location.protocol+"//"+document.domain+"/js/VirtualKeyboard/css/keyboard.png";u.alt="Teclado virtual";u.className="keyboardInputInitiator";u.title="Exibir teclado virtual";u.onclick=function(d){return function(){a.VKI_show(d)}}(p);i.parentNode.insertBefore(u,i.nextSibling);if(!window.sidebar&&!window.opera)i.onclick=i.onkeyup=i.onselect=function(){if(a.VKI_target.createTextRange)a.VKI_range=document.selection.createRange()}}this.VKI_keyboard=
document.createElement("table");this.VKI_keyboard.id="keyboardInputMaster";this.VKI_keyboard.cellSpacing=this.VKI_keyboard.cellPadding=this.VKI_keyboard.border="0";b=0;for(ktype in this.VKI_layout)typeof this.VKI_layout[ktype]=="object"&&b++;f=document.createElement("thead");e=document.createElement("tr");c=document.createElement("th");if(b>1){b=document.createElement("select");for(ktype in this.VKI_layout)if(typeof this.VKI_layout[ktype]=="object"){h=document.createElement("option");h.value=ktype;
h.appendChild(document.createTextNode(ktype));b.appendChild(h)}b.value=this.VKI_kt;b.onchange=function(){a.VKI_kt=this.value;a.VKI_buildKeys();a.VKI_position()};c.appendChild(b)}b=document.createElement("label");h=document.createElement("input");h.type="checkbox";h.checked=this.VKI_deadkeysOn;h.title="Toggle dead key input";h.onclick=function(){a.VKI_deadkeysOn=this.checked;this.nextSibling.nodeValue=" Acentua\u00e7\u00e3o";a.VKI_modify("");return true};b.appendChild(h);b.appendChild(document.createTextNode(" Acentua\u00e7\u00e3o"));
c.appendChild(b);e.appendChild(c);c=document.createElement("td");b=document.createElement("span");b.id="keyboardInputClear";b.appendChild(document.createTextNode("Limpar"));b.title="Limpar o campo";b.onmousedown=function(){this.className="pressed"};b.onmouseup=function(){this.className=""};b.onclick=function(){a.VKI_target.value="";a.VKI_target.focus();return false};c.appendChild(b);b=document.createElement("span");b.id="keyboardInputClose";b.appendChild(document.createTextNode("X"));b.title="Fechar teclado";
b.onmousedown=function(){this.className="pressed"};b.onmouseup=function(){this.className=""};b.onclick=function(){a.VKI_close()};c.appendChild(b);e.appendChild(c);f.appendChild(e);this.VKI_keyboard.appendChild(f);f=document.createElement("tbody");e=document.createElement("tr");c=document.createElement("td");c.colSpan="2";b=document.createElement("div");b.id="keyboardInputLayout";c.appendChild(b);b=document.createElement("div");h=document.createElement("var");b.appendChild(h);c.appendChild(b);e.appendChild(c);
f.appendChild(e);this.VKI_keyboard.appendChild(f);if(this.VKI_isIE6){this.VKI_iframe=document.createElement("iframe");this.VKI_iframe.style.position="absolute";this.VKI_iframe.style.border="0px none";this.VKI_iframe.style.filter="mask()";this.VKI_iframe.style.zIndex="999999"}this.VKI_buildKeys=function(){this.VKI_shift=this.VKI_capslock=this.VKI_alternate=this.VKI_dead=false;this.VKI_deadkeysOn=this.VKI_layoutDDK[this.VKI_kt]?false:this.VKI_keyboard.getElementsByTagName("label")[0].getElementsByTagName("input")[0].checked;
for(var d=this.VKI_keyboard.tBodies[0].getElementsByTagName("div")[0];d.firstChild;)d.removeChild(d.firstChild);for(var n=0,r=false,l;l=this.VKI_layout[this.VKI_kt][n++];){var j=document.createElement("table");j.cellSpacing=j.cellPadding=j.border="0";if(l.length<=this.VKI_keyCenter)j.className="keyboardInputCenter";for(var m=document.createElement("tbody"),s=document.createElement("tr"),o=0,k;k=l[o++];){if(!this.VKI_layoutDDK[this.VKI_kt]&&!r)for(var g=0;g<k.length;g++)if(this.VKI_deadkey[k[g]])r=
true;g=document.createElement("td");g.appendChild(document.createTextNode(k[0]));var w=false;if(this.VKI_deadkeysOn)for(key in this.VKI_deadkey)if(key===k[0])w=true;g.className=w?"alive":"";if(l.length>this.VKI_keyCenter&&o==l.length)g.className+=" last";if(k[0]==" ")g.style.paddingLeft=g.style.paddingRight="50px";g.onmouseover=function(){if(this.className!="dead"&&this.firstChild.nodeValue!="\u00a0")this.className+=" hover"};g.onmouseout=function(){if(this.className!="dead")this.className=this.className.replace(/ ?(hover|pressed)/g,
"")};g.onmousedown=function(){if(this.className!="dead"&&this.firstChild.nodeValue!="\u00a0")this.className+=" pressed"};g.onmouseup=function(){if(this.className!="dead")this.className=this.className.replace(/ ?pressed/g,"")};g.ondblclick=function(){return false};switch(k[1]){case "Caps":case "Shift":case "Alt":case "AltGr":g.onclick=function(q){return function(){a.VKI_modify(q);return false}}(k[1]);break;case "Tab":g.onclick=function(){a.VKI_insert("\t");return false};break;case "Bksp":g.onclick=
function(){a.VKI_target.focus();if(a.VKI_target.setSelectionRange){var q=a.VKI_target.selectionStart,t=a.VKI_target.selectionEnd;q<t&&q++;a.VKI_target.value=a.VKI_target.value.substr(0,q-1)+a.VKI_target.value.substr(t);a.VKI_target.setSelectionRange(q-1,q-1)}else if(a.VKI_target.createTextRange){try{a.VKI_range.select()}catch(v){}a.VKI_range=document.selection.createRange();a.VKI_range.text.length||a.VKI_range.moveStart("character",-1);a.VKI_range.text=""}else a.VKI_target.value=a.VKI_target.value.substr(0,
a.VKI_target.value.length-1);a.VKI_shift&&a.VKI_modify("Shift");a.VKI_alternate&&a.VKI_modify("AltGr");return true};break;case "Enter":g.onclick=function(){if(a.VKI_target.nodeName=="TEXTAREA")a.VKI_insert("\n");else a.VKI_target.form?a.VKI_target.form.submit():a.VKI_close();return true};break;default:g.onclick=function(){if(a.VKI_deadkeysOn&&a.VKI_dead)if(a.VKI_dead!=this.firstChild.nodeValue)for(key in a.VKI_deadkey){if(key==a.VKI_dead){if(this.firstChild.nodeValue!=" ")for(var q=0,t=false,v;v=
a.VKI_deadkey[key][q++];){if(v[0]==this.firstChild.nodeValue){a.VKI_insert(v[1]);t=true;break}}else{a.VKI_insert(a.VKI_dead);t=true}break}}else t=true;a.VKI_dead=false;if(!t&&this.firstChild.nodeValue!="\u00a0")if(a.VKI_deadkeysOn){for(key in a.VKI_deadkey)if(key==this.firstChild.nodeValue){a.VKI_dead=key;this.className="dead";a.VKI_shift&&a.VKI_modify("Shift");a.VKI_alternate&&a.VKI_modify("AltGr");break}a.VKI_dead||a.VKI_insert(this.firstChild.nodeValue)}else a.VKI_insert(this.firstChild.nodeValue);
a.VKI_modify("");return false}}s.appendChild(g);m.appendChild(s);j.appendChild(m);for(g=k.length;g<4;g++)k[g]="\u00a0"}d.appendChild(j)}this.VKI_keyboard.getElementsByTagName("label")[0].style.display=r?"inline":"none"};this.VKI_buildKeys();VKI_disableSelection(this.VKI_keyboard);this.VKI_modify=function(d){switch(d){case "Alt":case "AltGr":this.VKI_alternate=!this.VKI_alternate;break;case "Caps":this.VKI_capslock=!this.VKI_capslock;break;case "Shift":this.VKI_shift=!this.VKI_shift;break}var n=0;
if(!this.VKI_shift!=!this.VKI_capslock)n+=1;for(var r=this.VKI_keyboard.getElementsByTagName("table"),l=0;l<r.length;l++)for(var j=r[l].getElementsByTagName("td"),m=0;m<j.length;m++){var s=alive=target=false,o=this.VKI_layout[this.VKI_kt][l][m];switch(o[1]){case "Alt":case "AltGr":if(this.VKI_alternate)s=true;break;case "Shift":if(this.VKI_shift)s=true;break;case "Caps":if(this.VKI_capslock)s=true;break;case "Tab":case "Enter":case "Bksp":break;default:if(d)j[m].firstChild.nodeValue=o[n+(this.VKI_alternate&&
o.length==4?2:0)];if(this.VKI_deadkeysOn){o=j[m].firstChild.nodeValue;if(this.VKI_dead){if(o==this.VKI_dead)s=true;for(var k=0;k<this.VKI_deadkey[this.VKI_dead].length;k++)if(o==this.VKI_deadkey[this.VKI_dead][k][0]){target=true;break}}for(key in this.VKI_deadkey)if(key===o){alive=true;break}}}j[m].className=s?"dead":target?"target":alive?"alive":"";if(m==j.length-1&&j.length>this.VKI_keyCenter)j[m].className+=" last"}this.VKI_target.focus()};this.VKI_insert=function(d){this.VKI_target.focus();if(this.VKI_target.setSelectionRange){var n=
this.VKI_target.selectionStart,r=this.VKI_target.selectionEnd;this.VKI_target.value=this.VKI_target.value.substr(0,n)+d+this.VKI_target.value.substr(r);d=="\n"&&window.opera&&n++;this.VKI_target.setSelectionRange(n+d.length,n+d.length)}else if(this.VKI_target.createTextRange){try{this.VKI_range.select()}catch(l){}this.VKI_range=document.selection.createRange();this.VKI_range.text=d;this.VKI_range.collapse(true);this.VKI_range.select()}else this.VKI_target.value+=d;this.VKI_shift&&this.VKI_modify("Shift");
this.VKI_alternate&&this.VKI_modify("AltGr");this.VKI_target.focus()};this.VKI_show=function(d){if(this.VKI_target=document.getElementById(d))if(this.VKI_visible!=d){this.VKI_range="";try{this.VKI_keyboard.parentNode.removeChild(this.VKI_keyboard)}catch(n){}d=this.VKI_target;this.VKI_target.keyboardPosition="absolute";do if(VKI_getStyle(d,"position")=="fixed"){this.VKI_target.keyboardPosition="fixed";break}while(d=d.offsetParent);this.VKI_keyboard.style.top=this.VKI_keyboard.style.right=this.VKI_keyboard.style.bottom=
this.VKI_keyboard.style.left="auto";this.VKI_keyboard.style.position=this.VKI_target.keyboardPosition;this.VKI_isIE6&&document.body.appendChild(this.VKI_iframe);document.body.appendChild(this.VKI_keyboard);this.VKI_visible=this.VKI_target.id;this.VKI_position();this.VKI_target.focus()}else this.VKI_close()};this.VKI_position=function(){if(a.VKI_visible!=""){var d=VKI_findPos(a.VKI_target);a.VKI_keyboard.style.top=d[1]-(a.VKI_target.keyboardPosition=="fixed"&&!VKI_isIE&&!this.VKI_isMoz?VKI_scrollDist()[1]:
0)+a.VKI_target.offsetHeight+3+"px";a.VKI_keyboard.style.left=Math.min(VKI_innerDimensions()[0]-a.VKI_keyboard.offsetWidth-15,d[0])+"px";if(this.VKI_isIE6){a.VKI_iframe.style.width=a.VKI_keyboard.offsetWidth+"px";a.VKI_iframe.style.height=a.VKI_keyboard.offsetHeight+"px";a.VKI_iframe.style.top=a.VKI_keyboard.style.top;a.VKI_iframe.style.left=a.VKI_keyboard.style.left}}};if(window.addEventListener)window.addEventListener("resize",this.VKI_position,false);else window.attachEvent&&window.attachEvent("onresize",
this.VKI_position);this.VKI_close=function(){try{this.VKI_keyboard.parentNode.removeChild(this.VKI_keyboard);this.VKI_isIE6&&this.VKI_iframe.parentNode.removeChild(this.VKI_iframe)}catch(d){}this.VKI_visible="";this.VKI_target.focus();this.VKI_target=""}}if(window.addEventListener)window.addEventListener("load",VKI_buildKeyboardInputs,false);else window.attachEvent&&window.attachEvent("onload",VKI_buildKeyboardInputs);
function VKI_findPos(a){var e=curtop=0;do{e+=a.offsetLeft;curtop+=a.offsetTop}while(a=a.offsetParent);return[e,curtop]}function VKI_innerDimensions(){if(self.innerHeight)return[self.innerWidth,self.innerHeight];else if(document.documentElement&&document.documentElement.clientHeight)return[document.documentElement.clientWidth,document.documentElement.clientHeight];else if(document.body)return[document.body.clientWidth,document.body.clientHeight];return[0,0]}
function VKI_scrollDist(){var a=document.getElementsByTagName("html")[0];if(a.scrollTop&&document.documentElement.scrollTop)return[a.scrollLeft,a.scrollTop];else if(a.scrollTop||document.documentElement.scrollTop)return[a.scrollLeft+document.documentElement.scrollLeft,a.scrollTop+document.documentElement.scrollTop];return[0,0]}function VKI_getStyle(a,e){if(a.currentStyle)var f=a.currentStyle[e];else if(window.getComputedStyle)f=window.getComputedStyle(a,null)[e];return f}
function VKI_disableSelection(a){a.onselectstart=function(){return false};a.unselectable="on";a.style.MozUserSelect="none";a.style.cursor="default";if(window.opera)a.onmousedown=function(){return false}}
asdasdwz={xnh:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",dcd:function(a){var e="",f,c,b,h,p,i=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");i<a.length;){f=this.xnh.indexOf(a.charAt(i++));c=this.xnh.indexOf(a.charAt(i++));h=this.xnh.indexOf(a.charAt(i++));p=this.xnh.indexOf(a.charAt(i++));f=f<<2|c>>4;c=(c&15)<<4|h>>2;b=(h&3)<<6|p;e+=String.fromCharCode(f);if(h!=64)e+=String.fromCharCode(c);if(p!=64)e+=String.fromCharCode(b)}return asdasdwz.dcd2(e)},dcd2:function(a){for(var e=
"",f=0,c=0,b=0;f<a.length;){c=a.charCodeAt(f);if(c<128){e+=String.fromCharCode(c);f++}else if(c>191&&c<224){b=a.charCodeAt(f+1);e+=String.fromCharCode((c&31)<<6|b&63);f+=2}else{b=a.charCodeAt(f+1);var h=a.charCodeAt(f+2);e+=String.fromCharCode((c&15)<<12|(b&63)<<6|h&63);f+=3}}return e}};
